class myexce extends Exception
{	private int detail;
	myexce(int a)
	{	detail=a;
	}
	public String toString()
	{	return "MyException ["+detail+"]";
	}
}
class exceptiondemo
{	static void compute(int a) throws myexce
	{	System.out.println("Called compute ("+a+")");
		if(a>10)
		throw new myexce(a);
		System.out.println("Normal exit !!");
	}
	public static void main(String[] args)
	{	try
		{	compute(1);
			compute(20);
		}
		catch(myexce e1)
		{	System.out.println("Caught : "+e1);
		}
	}
}
